### ISSUE TITLE
Ask for questions about writing

### ISSUE THREAD

**Issue by nonacosa** [mk965/mengke.me#12]
Your project is very beautiful. I am learning the front end. I forked your project, but I have a question: How did you generate the mdx file in the/data directory, and what editor or plug-in did you use?

```md
---
heading: 'Getting Spotify token'
title: 'Getting Spotify token to display now playing track on your website'
date: '2023-09-30'
icon: 'Spotify'
draft: false
summary: 'Retrieve a Spotify access token to display the currently playing track on your website or application.'
tags: [spotify, nowplaying, spotify-api, nextjs]
---
```

Like the marks above, are they all written by manually ? OR use some 'tools' ?      Is the directory also created manually ？

**Comment by mk965** [comment]
You will find that the syntax of `mdx` is basically the same as `md`, but the functions are expanded on the md file.
So if there are no components in your article, you can use any markdown editor.

The "fields" part is all written by manually.

At present, I have not considered using a dedicated editor or developing a backend to write articles, because I think it is better to write `md` files directly.

**Comment by nonacosa** [comment]
Ok I've got it, I'm going to try to use https://github.com/nonacosa/notion-site to sync the article, your answer help me a lot, thank you
